ARCHIVE=xsesta07.zip 

test:
	@echo "[info] performing test 01 (ARCHIVE - is_it_ok)"
	./is_it_ok.sh ../$(ARCHIVE) ./whole_test_01

artifacts:
	@echo "[info] creating artifacts for test 01"
	cp -rf ./whole_test_01 ../test_artifacts/

