.TH SECRET 1

.SH NAME
secret \- Send encrypted file via network

.SH SYNOPSIS
.B secret
\fB\-r\fR \fI<file>\fR
\fB\-s\fR \fI<ip|hostname>\fR
[\fB\-l\fR ]

.SH DESCRIPTION
.B secret
Application encrypt file via AES symetric encrypt algorithm and send to specified ip or hostname hidden inside ICMP packets

.SH OPTIONS

.TP
.BR \-r
Specify file which will be encrypted and sended.

.TP
.BR \-s
Specify ip or hostname

.TP
.BR \-l
Enable listening mode to accept encrypted files