{
 "title": "MPR Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Microservice CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Microservices requests received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_requests_received_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Microservice memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Microservices requests failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_failed_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projects health",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "clamp_min(count(aspnetcore_healthcheck_status{job=\"Projects_microservice\"}) or on() vector(0), 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opportunities health",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "clamp_min(count(aspnetcore_healthcheck_status{job=\"Opportunities_microservice\"}), 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project phases health",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "clamp_min(count(aspnetcore_healthcheck_status{job=\"Project_phases_microservice\"}), 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project phase microservice health",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{job=\"Project_phases_microservice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Opportunities microservice health",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{job=\"Opportunities_microservice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Risk microservice health",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{job=\"Risks_microservice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Risk templates health",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "clamp_min(count(aspnetcore_healthcheck_status{job=\"Risk_templates_microservice\"}), 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Employees health",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "clamp_min(count(aspnetcore_healthcheck_status{job=\"Employees_microservice\"}), 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Risk health",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "clamp_min(count(aspnetcore_healthcheck_status{job=\"Risks_microservice\"}), 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Risk template microservice health",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{job=\"Risk_templates_microservice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Projects microservice health",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{job=\"Projects_microservice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}